[package]
name = "graphics"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.21.0"
encase = "0.10.0"
image = "0.25.6"
pollster = "0.4.0"
wgpu = "24.0.1"
winit = "0.30.9"

[build-dependencies]
webp = "0.3.0"
